services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${BD_URL}
    volumes:
      - ./app:/app

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${BD_USERNAME}
      - POSTGRES_PASSWORD=${BD_PASSWORD}
      - POSTGRES_DB=jvlink_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BD_USERNAME} -d jvlink_db"]
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
